/teleop_node:
  ros__parameters:
    axis_linear: 
      x: 1
      y: 3
    scale_linear: 
      x: 0.2
      y: 0.2
    
    axis_angular:
      yaw: 0.2
    scale_angular:
      yaw: 0.2

    require_enable_button: false


/twist_mux:
  ros_parameters:
    topics:
      automatic_navigation:
        topic: /cmd_vel
        timeout: 0.5
        priority: 1
      joystick:
        topic: /cmd_vel_joy
        timeout: 0.5
        priority: 5
      keyboard:
        topic: /cmd_vel_key
        timeout: 0.5
        priority: 10
    