amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    update_min_a: 0.1
    update_min_d: 0.15
    laser_model_type: "likelihood_field"
    scan_topic: "/mir_scan"
    transform_tolerance: 1.0
    save_pose_rate: 0.5
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5
    sigma_hit: 0.2
    laser_likelihood_max_dist: 2.0

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 10.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.05
      stateful: True
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      max_vel_x: 0.26
      max_vel_theta: 1.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      vx_samples: 20
      vtheta_samples: 20
      sim_time: 1.7
      critics: ["RotateToGoal", "PathAlign", "PathDist", "GoalDist"]

local_costmap:
  ros__parameters:
    use_sim_time: False
    update_frequency: 5.0
    publish_frequency: 5.0
    global_frame: odom
    robot_base_frame: base_link
    rolling_window: True
    width: 5.0
    height: 5.0
    resolution: 0.05
    footprint: '[ [0.54, 0.38], [-0.54, 0.38], [-0.54, -0.38], [0.54, -0.38] ]'
    footprint_padding: 0.01
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: True
      observation_sources: laser_scan camera_floor_left camera_floor_right
      
      laser_scan:
        topic: /mir_scan
        data_type: LaserScan
        clearing: true
        marking: true
        inf_is_valid: true

      camera_floor_left:
        topic: /camera_floor_left/transformed_obstacles
        data_type: PointCloud2
        clearing: true
        marking: true
        obstacle_max_range: 3.0
        obstacle_min_range: 0.05
        raytrace_max_range: 3.5
        raytrace_min_range: 0.05

      camera_floor_right:
        topic: /camera_floor_right/transformed_obstacles
        data_type: PointCloud2
        clearing: true
        marking: true
        obstacle_max_range: 3.0
        obstacle_min_range: 0.05
        raytrace_max_range: 3.5
        raytrace_min_range: 0.05
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
      cost_scaling_factor: 3.0


global_costmap:
  ros__parameters:
    use_sim_time: False
    update_frequency: 1.0
    publish_frequency: 1.0
    global_frame: map
    robot_base_frame: base_link
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: True
      observation_sources: laser_scan camera_floor_left camera_floor_right
      
      laser_scan:
        topic: /mir_scan
        data_type: LaserScan
        clearing: true
        marking: true
        inf_is_valid: true

      camera_floor_left:
        topic: /camera_floor_left/transformed_obstacles
        data_type: PointCloud2
        clearing: true
        marking: true
        obstacle_max_range: 3.0
        obstacle_min_range: 0.05
        raytrace_max_range: 3.5
        raytrace_min_range: 0.05

      camera_floor_right:
        topic: /camera_floor_right/transformed_obstacles
        data_type: PointCloud2
        clearing: true
        marking: true
        obstacle_max_range: 3.0
        obstacle_min_range: 0.05
        raytrace_max_range: 3.5
        raytrace_min_range: 0.05
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
      cost_scaling_factor: 3.0
